<?php echo($this->render('header.tpl.phtml'));?>
<div class="center_block">
	<h2>SISTEMA DE TRAMITA&Ccedil;&Atilde;O DE DOCUMENTOS</h2>
	<h2>UNIDADES DA PREFEITURA DE GUARULHOS</h2>
	<h2>Vers&atilde;o 1.0</h2>
	<p>
	Utilize o menu acima para navegar no sistema
	</p>
	<p id="footer_dev">
	Desenvolvido pela equipe de desenvolvimento da Proguaru
	<br />
	Progresso de desenvolvimento de Guarulhos S.A.
	<br />
	10/2009
	</p>
</div>
<?php echo($this->render('footer.tpl.phtml'));?>