<?php echo($this->documentoSearchForm);?>

<br />

<?php
if(count($this->documentos)):
?>
<form name="formDocumentos" id="formDocumentos" action="<?php echo($this->baseUrl);?>/<?php echo($this->controllerName);?>/index" method="post">
<table border="0">
	<tr>
		<th>&nbsp;</th>
		<th>Nº Documento</th>
		<th>Data Elaboração</th>
		<th>Tipo Documento</th>
		<th>Usuário</th>
		<th>Orgão Origem</th>
		<th>Assunto</th>
		<th>Complemento Assunto</th>
	</tr>
<?php
	foreach($this->paginator as $key => $documento):
		$rowColor = (($key + 1) % 2) == 0 ? "#E4E4E4" : "#FFFFFF";
?>
	<tr style="cursor:pointer;_cursor:hand;background:<?php echo($rowColor);?>" 
	    onclick="document.getElementById('dc_id[<?php echo($documento['dc_id']); ?>]').checked = true"
	    onmouseover="this.style.background = '#E1EDF9'; this.style.fontWeight = 'bold';"
	    onmouseout="this.style.background = '<?php echo($rowColor);?>'; this.style.fontWeight = 'normal';">
		<td><input type="checkbox" name="dc_id[]" id="dc_id[<?php echo($documento['dc_id']); ?>]" value="<?php echo($documento['dc_id']); ?>" /></td>
		<td>
		<?php
		// Caso o documento possuir arquivo PDF cadastrado linca para visualização do arquivo PDF
		if($documento['possuiArquivo'])
		{
		?>
		<a href="<?php echo($this->baseUrl);?>/documento/viewarquivo/id/<?php echo($this->escape($documento['dc_id']));?>" target="_blank" alt="Clique Aqui para Visualizar o PDF" title="Clique Aqui para Visualizar o PDF"><?php echo($this->escape($documento['dc_numero']));?></a>
		<?php
		}
		else
		{
			echo $this->escape($documento['dc_numero']);
		}
		?>
		</td>
		<td>
			<?php
			$objDate 	= new Zend_Date($this->escape($documento['dc_data_elaboracao']));
			$objLocale  	= new Zend_Locale('pt_BR');
			Zend_Date::setOptions(array('format_type' => 'php'));
			$fmdc_data_elaboracao = $objDate->toString('d/m/Y'); /** pt_BR format */
			
			//echo($this->escape($documento['dc_data_elaboracao']));
			echo($fmdc_data_elaboracao);
			?>
		</td>
		<td><?php echo($this->escape($documento['td_descricao'])); ?></td>
		<td><?php echo($documento['us_id'] == $this->userId ? "<strong>".$this->userLogin."</strong>" : $this->escape($documento['us_nome'])); ?></td>
		<td><?php echo(strlen($documento['orgao_origem']) ? $this->escape(trim($documento['orgao_origem'])) : '&nbsp;'); ?></td>
		<td><?php echo($this->escape(trim($documento['as_descricao']))); ?></td>
		<td><?php echo(strlen($documento['dc_compl_assunto']) ? $this->escape(trim($documento['dc_compl_assunto'])) : '&nbsp;'); ?></td>
	</tr>
<?php
	endforeach;
?>
	<tr>
		<td colspan="9" style="text-align:right;width:70px"><input type="submit" value="Tramitar" /></td>
	</tr>
</table>
</form>
<?php
else:
?>
	<p><strong><?php echo($this->userLogin);?></strong>, não há documento.</p>
<?php
endif;
?>

<?php
//echo $this->paginationControl($this->paginator, 'Sliding', 'pagination/partial.phtml');
//echo($this->paginator);
echo($this->render('pagination/partial.phtml'));
?>
