<?php echo $this->formSearch; ?>
<br>
<table border="1">
	<tr>
		<th>Id</th>
		<th>Tipo Documento</th>
		<th>Usu&aacute;rio</th>
		<th>Usu&aacute;rio</th>
	</tr>
<?php
	foreach ($this->documentos as $key => $documento)
	{
?>
	<tr>
		<td><?php echo $documento->id;?></td>
		<td><?php echo $documento->td_id;?></td>
		<td><?php echo $documento->dc_data_elaboracao;?></td>
		<td><?php echo $documento->us_id;?></td>
	</tr>
<?php
	}
?>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination/search.phtml'); ?>
</div>
</body>
</html>