	</div>
	<!-- /PANEL -->
	<div id="footer">
		<p id="footer_dev">
			Desenvolvido e Mantido pela Equipe de Desenvolvimento da Proguaru<br />
			Progresso e Desenvolvimento de Guarulhos S.A.<br />
			2009<br />
			Requisitos: Internet Explorer 7 ou superior, Firefox 3.0 ou superior e Adobe Flash Player 10 ou superior e Adobe Reader 9 ou superior<br />
		</p>
	</div>
	<div id="divTopoFixa"><a href="#header">Topo</a></div>
</div>
<!-- /CONTENT -->
</body>
</html>