<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<title><?php echo $this->escape($this->title); ?></title>
	<link rel="stylesheet" href="<?php echo($this->baseUrl);?>/public/styles/default.css" />
</head>
<body>
<!-- CONTENT -->
<div id="content">
	<h3><?php echo $this->welcomeMsg;?></h3>
	<a href="<?php echo $this->baseUrl;?>/">index</a> | 
	<a href="<?php echo $this->baseUrl;?>/login/logout/">logout</a>
	
	<a href="<?php echo $this->baseUrl;?>/index/listuser/id/4">id = 4</a> | 
	<a href="<?php echo $this->baseUrl;?>/documento/">Documento</a> | 
	<a href="<?php echo $this->baseUrl;?>/login/logout/">Logout</a>
	<h1><?php echo $this->detail;?></h1>
	
	<hr />