<?php echo($this->render('header.tpl.phtml'));?>
<h1><?php echo($this->title);?></h1>
<?php echo $this->formSearch; ?>
<table border="1">
	<tr>
		<th>Descrição</th>
		<th>Data de Cadastro</th>
		<th>Usuário</th>
	</tr>
<?php
if(count($this->orgaosexternos)):
	foreach($this->orgaosexternos as $key => $orgaoexterno):
?>
	<tr>
		<td><?php echo($this->escape(trim($orgaoexterno['oe_descricao']))); ?></td>
		<td><?php echo($this->escape($orgaoexterno['oe_data_cadastro'])); ?></td>
		<td><?php echo($this->escape($orgaoexterno['us_id']) == $this->userId ? "<strong>".utf8_encode($this->userLogin)."</strong>" : utf8_encode($orgaoexterno['us_nome'])); ?></td>
		<?php
		// Caso for o gestor (Tipo Usuário com ID = 1) libera edição e desativação
		if($this->userTipoId == 1):
		?>
		<td>
			<a href="<?php echo($this->baseUrl);?>/orgaoexterno/edit/id/<?php echo($orgaoexterno['oe_id']);?>"><img src="<?php echo($this->baseUrl);?>/public/images/icons/edit.png" width="30" height="27" alt="Editar" title="Editar" border="0" /></a>
			<a href="<?php echo $this->baseUrl;?>/orgaoexterno/delete/id/<?php echo($orgaoexterno['oe_id']);?>"><img src="<?php echo($this->baseUrl);?>/public/images/icons/delete.png" width="30" height="27" alt="Desativar" title="Desativar" border="0" /></a>
		</td>
		<?php
		endif;
		?>
	</tr>
<?php
	endforeach;
endif;
?>
</table>
<?php #echo $this->paginationControl($this->paginator, 'Sliding', 'pagination/search.phtml'); ?>
<?php echo($this->render('footer.tpl.phtml'));?>