<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Página de Erro Tramita&ccedil;&atilde;o de Documentos</title>
</head>
<body>
  
  <?php echo var_dump($this);?>

  <h1>An error occurred</h1> 
  <h2><?php echo $this->message ?></h2> 

  <?php if ('development' == $this->env): ?> 
  
  <h3>Exception information:</h3> 
  <p> 
      <b>Message:</b> <?php echo $this->exception->getMessage() ?> 
  </p> 

  <h3>Stack trace:</h3> 
  <pre><?php echo $this->exception->getTraceAsString() ?> 
  </pre> 

  <h3>Request Parameters:</h3> 
  <pre><?php var_dump($this->request->getParams()) ?> 
  </pre> 
  <?php endif ?>
  
</body>
</html>